
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewProject
{

using System;
    using System.Collections.Generic;
    
public partial class BAOCAOTON
{

    public int Thang { get; set; }

    public int Nam { get; set; }

    public int MaSP { get; set; }

    public Nullable<int> TonDau { get; set; }

    public Nullable<int> TonCuoi { get; set; }

    public Nullable<int> SLMuaVao { get; set; }

    public Nullable<int> SLBanRa { get; set; }

    public int MaDVT { get; set; }



    public virtual DONVITINH DONVITINH { get; set; }

    public virtual SANPHAM SANPHAM { get; set; }

}

}
