
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewProject
{

using System;
    using System.Collections.Generic;
    
public partial class CT_PBH
{

    public int MaPBH { get; set; }

    public int MaSP { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<long> DonGiaBan { get; set; }

    public Nullable<long> ThanhTien { get; set; }



    public virtual PHIEUBANHANG PHIEUBANHANG { get; set; }

    public virtual SANPHAM SANPHAM { get; set; }

}

}
