
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewProject
{

using System;
    using System.Collections.Generic;
    
public partial class CT_PDV
{

    public int MaPDV { get; set; }

    public int MaDV { get; set; }

    public Nullable<long> DonGiaDV { get; set; }

    public Nullable<long> DonGiaDuocTinh { get; set; }

    public Nullable<int> SoLuongDV { get; set; }

    public Nullable<long> ThanhTien { get; set; }

    public Nullable<int> MaTT { get; set; }

    public Nullable<System.DateTime> NgayGiao { get; set; }

    public string TinhTrang { get; set; }

    public Nullable<long> TraTruoc { get; set; }

    public Nullable<long> ConLai { get; set; }

    public Nullable<long> ChiPhiRiengDV { get; set; }



    public virtual PHIEUDV PHIEUDV { get; set; }

    public virtual DICHVU DICHVU { get; set; }

}

}
