

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewProject
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DB_QLKDEntities : DbContext
{
    public DB_QLKDEntities()
        : base("name=DB_QLKDEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<BAOCAOTON> BAOCAOTONs { get; set; }

    public virtual DbSet<CT_PBH> CT_PBH { get; set; }

    public virtual DbSet<CT_PDV> CT_PDV { get; set; }

    public virtual DbSet<CT_PMH> CT_PMH { get; set; }

    public virtual DbSet<DICHVU> DICHVUs { get; set; }

    public virtual DbSet<DONVITINH> DONVITINHs { get; set; }

    public virtual DbSet<LOAISP> LOAISPs { get; set; }

    public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }

    public virtual DbSet<PHIEUBANHANG> PHIEUBANHANGs { get; set; }

    public virtual DbSet<PHIEUDV> PHIEUDVs { get; set; }

    public virtual DbSet<PHIEUMUAHANG> PHIEUMUAHANGs { get; set; }

    public virtual DbSet<SANPHAM> SANPHAMs { get; set; }

    public virtual DbSet<LOGIN> LOGINs { get; set; }

}

}

