
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewProject
{

using System;
    using System.Collections.Generic;
    
public partial class DICHVU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DICHVU()
    {

        this.CT_PDV = new HashSet<CT_PDV>();

    }


    public int MaDV { get; set; }

    public string LoaiDV { get; set; }

    public Nullable<long> DonGiaDV { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CT_PDV> CT_PDV { get; set; }

}

}
