
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NewProject
{

using System;
    using System.Collections.Generic;
    
public partial class NHACUNGCAP
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NHACUNGCAP()
    {

        this.PHIEUMUAHANGs = new HashSet<PHIEUMUAHANG>();

    }


    public int MaNCC { get; set; }

    public string DiaChiNCC { get; set; }

    public string SDTNCC { get; set; }

    public string TenNCC { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PHIEUMUAHANG> PHIEUMUAHANGs { get; set; }

}

}
